<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>icbs-interfaces</groupId>
	<artifactId>icbs-interface</artifactId>
	<version>2.0.0</version>
	<name>icbs-interface</name>
	<description>Servicios de ICBS</description>
	<properties>
		<maven.compiler.source>8</maven.compiler.source>
		<maven.compiler.target>8</maven.compiler.target>
	</properties>
	<build>
		<sourceDirectory>src/main/java</sourceDirectory>
		<testSourceDirectory>src/test/java</testSourceDirectory>
		<testOutputDirectory>target/test-classes</testOutputDirectory>
		<resources>
			<resource>
				<filtering>false</filtering>
				<directory>src/main/config</directory>
			</resource>
		</resources>
		<outputDirectory>target/classes</outputDirectory>
	</build>
	<dependencies>
		<dependency>
			<groupId>icbs-interfaces</groupId>
			<artifactId>icbs-interface-core</artifactId>
			<version>2.0.0</version>
		</dependency>

	</dependencies>
	<!--  <distributionManagement>-->
	<!--	    <repository>-->
	<!--	        <id>central</id>-->
	<!--	        <name>1f48f5d16364-releases</name>-->
	<!--	        <url>http://192.168.1.162:8082/artifactory/libs-release</url>-->
	<!--	    </repository>-->
	<!--	    <snapshotRepository>-->
	<!--	        <id>snapshots</id>-->
	<!--	        <name>1f48f5d16364-snapshots</name>-->
	<!--	        <url>http://192.168.1.162:8082/artifactory/libs-snapshot</url>-->
	<!--	    </snapshotRepository>-->
	<!--</distributionManagement>-->
	<profiles>
		<profile>
			<id>develop</id>
			<distributionManagement>
				<repository>
					<id>central</id>
					<name>1f48f5d16364-releases</name>
					<url>http://192.168.1.145:8082/artifactory/develop</url>
				</repository>
				<snapshotRepository>
					<id>snapshots</id>
					<name>1f48f5d16364-snapshots</name>
					<url>http://192.168.1.145:8082/artifactory/develop</url>
				</snapshotRepository>
			</distributionManagement>
		</profile>
		<profile>
			<id>release</id>
			<distributionManagement>
			    <repository>
			        <id>central</id>
			        <name>1f48f5d16364-releases</name>
			        <url>http://192.168.1.145:8082/artifactory/release</url>
			    </repository>
			    <snapshotRepository>
			        <id>snapshots</id>
			        <name>1f48f5d16364-snapshots</name>
			        <url>http://192.168.1.145:8082/artifactory/release</url>
			    </snapshotRepository>
			</distributionManagement>	
		</profile>
		<profile>
			<id>project_release</id>
			<distributionManagement>
			    <repository>
			        <id>central</id>
			        <name>1f48f5d16364-releases</name>
			        <url>http://192.168.1.145:8082/artifactory/project_release</url>
			    </repository>
			    <snapshotRepository>
			        <id>snapshots</id>
			        <name>1f48f5d16364-snapshots</name>
			        <url>http://192.168.1.145:8082/artifactory/project_release</url>
			    </snapshotRepository>
			</distributionManagement>
		</profile>
	</profiles>
</project>